// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenSource creates a new instance of MockTokenSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenSource {
	mock := &MockTokenSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenSource is an autogenerated mock type for the TokenSource type
type MockTokenSource struct {
	mock.Mock
}

type MockTokenSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenSource) EXPECT() *MockTokenSource_Expecter {
	return &MockTokenSource_Expecter{mock: &_m.Mock}
}

// Token provides a mock function for the type MockTokenSource
func (_mock *MockTokenSource) Token() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenSource_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockTokenSource_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
func (_e *MockTokenSource_Expecter) Token() *MockTokenSource_Token_Call {
	return &MockTokenSource_Token_Call{Call: _e.mock.On("Token")}
}

func (_c *MockTokenSource_Token_Call) Run(run func()) *MockTokenSource_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenSource_Token_Call) Return(s string, err error) *MockTokenSource_Token_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenSource_Token_Call) RunAndReturn(run func() (string, error)) *MockTokenSource_Token_Call {
	_c.Call.Return(run)
	return _c
}

// Invalidate provides a mock function for the type MockTokenSource
func (_mock *MockTokenSource) Invalidate() {
	_mock.Called()
}

// MockTokenSource_Invalidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invalidate'
type MockTokenSource_Invalidate_Call struct {
	*mock.Call
}

// Invalidate is a helper method to define mock.On call
func (_e *MockTokenSource_Expecter) Invalidate() *MockTokenSource_Invalidate_Call {
	return &MockTokenSource_Invalidate_Call{Call: _e.mock.On("Invalidate")}
}

func (_c *MockTokenSource_Invalidate_Call) Run(run func()) *MockTokenSource_Invalidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTokenSource_Invalidate_Call) Return() *MockTokenSource_Invalidate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTokenSource_Invalidate_Call) RunAndReturn(run func()) *MockTokenSource_Invalidate_Call {
	_c.Call.Return(run)
	return _c
}

