stages:
  - build
  - deploy

variables:
  STAGING_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  STAGING_LATEST_IMAGE: $CI_REGISTRY_IMAGE:staging
  PROD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  PROD_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  STAGING_URL: "https://api.vh-staging.2serv.eu/profiles/" # this is not used by the service
  PRODUCTION_URL: "https://kli.one/register/"
build_staging:
  image: docker:latest
  stage: build
  tags:
    - staging
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --cache-from $STAGING_LATEST_IMAGE  -t $STAGING_IMAGE .
    - docker tag $STAGING_IMAGE $STAGING_LATEST_IMAGE
    - docker push $STAGING_IMAGE
    - docker push $STAGING_LATEST_IMAGE
  only:
    - master

deploy_staging:
  #image: tmaier/docker-compose:latest
  variables: 
    # we want to use the db in staging server itself.
    DB_HOST: "profiledb" #"${DEV_PG_HOST}" 
    DB_PORT: 5432 ${DEV_PG_PORT} 
    DB_USER: ${DEV_REG_PG_USER}
    DB_DATABASE: ${DEV_PROFILE_PG_DBNAME}
    DB_PASSWORD: "password" #${DEV_PG_PWD}
    DATABASE_URL: "postgres://${DEV_REG_PG_USER}:password@profiledb:5432/${DEV_PROFILE_PG_DBNAME}"
    APP_PORT: ":7471"
    APP_MODE: "dev"
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.2.0
  stage: deploy
  tags:
    - staging
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - "[ ! -d /opt/srv-profile-db ] && mkdir /opt/srv-profile-db"
    - cp -f db/initial.sql /opt/srv-profile-db/initial.sql
    - IMAGE_NAME=$STAGING_IMAGE docker-compose up -d --remove-orphans
  only:
    - master


build_production:
  image: docker:latest
  stage: build
  tags:
    - dockerbuild
  services:
    - docker:19.03.12-dind
  script:
    - env
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build -t $PROD_IMAGE .
    - docker push $PROD_IMAGE
  only:
    - tags

deploy_production:
  #image: tmaier/docker-compose:latest
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.2.0
  stage: deploy
  tags:
    - production
  variables: 
    # we want to use the db in staging server itself.
    DB_HOST: "${PROD_PG_HOST}" 
    DB_PORT: ${PROD_PG_PORT} 
    DB_USER: ${PROD_PROFILE_DB_USER}
    DB_DATABASE: ${PROD_PROFILE_DB_NAME}
    DB_PASSWORD: ${PROD_PROFILE_DB_PASS}
    APP_PORT: ":7471"
    APP_MODE: "prod"
    DATABASE_URL: "postgres://${PROD_PROFILE_DB_USER}:${PROD_PROFILE_DB_PASS}@${PROD_PG_HOST}:${PROD_PG_PORT}/${PROD_PROFILE_DB_NAME}"
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - IMAGE_NAME=$PROD_IMAGE docker-compose up -d vh-srv-profile
  only:
    - tags
  when: manual



# #======
# stages:
#   - publish
#   - deploy
#   - publish_prod
#   - deploy_prod
#   - deploy_stand

# variables:
#   IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA
#   PROD_IMAGE: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:prod_$CI_COMMIT_SHORT_SHA

# publish:
#   image: docker:latest
#   stage: publish
#   tags:
#     - dockerbuild
#   services:
#     - docker:19.03.12-dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     - docker build -t $IMAGE .
#     - docker push $IMAGE
#   only:
#     - development

# deploy:
#   image: docker:latest
#   stage: deploy
#   tags:
#     - dockerbuild
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $IMAGE"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker container rm -f vh-srv-profile || true"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d --net=vh --name vh-srv-profile --memory="200m" --cpus="0.5" --restart always -p 7471:7471 $IMAGE "
#   environment:
#     name: development
#     url: http://51.15.238.1
#   when: manual
#   only:
#     - development

# publish_prod:
#   image: docker:latest
#   stage: publish
#   tags:
#     - dockerbuild
#   services:
#     - docker:19.03.12-dind
#   script:
#     - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
#     - docker build -t $PROD_IMAGE .
#     - docker push $PROD_IMAGE
#   only:
#     - master

# deploy_prod:
#   image: docker:latest
#   stage: deploy_prod
#   tags:
#     - dockerbuild
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_IP "docker pull $PROD_IMAGE"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_IP "docker container rm -f prod-vh-srv-profile || true"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $PROD_SERVER_USER@$PROD_SERVER_IP "docker run -d --net=vh --name prod-vh-srv-profile --memory="200m" --cpus="0.5" --restart always -p 7471:7471 $PROD_IMAGE "
#   when: manual
#   only:
#     - master

# deploy_stand:
#   image: docker:latest
#   stage: deploy_stand
#   tags:
#     - dockerbuild
#   script:
#     - chmod og= $ID_RSA
#     - apk update && apk add openssh-client
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $STAND_SERVER_USER@$STAND_SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $STAND_SERVER_USER@$STAND_SERVER_IP "docker pull $PROD_IMAGE"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $STAND_SERVER_USER@$STAND_SERVER_IP "docker container rm -f prod-vh-srv-profile || true"
#     - ssh -i $ID_RSA -o StrictHostKeyChecking=no $STAND_SERVER_USER@$STAND_SERVER_IP "docker run -d --net=vh --name prod-vh-srv-profile --memory="200m" --cpus="0.5" --restart always -p 7471:7471 $PROD_IMAGE "
#   when: manual
#   only:
#     - master
