stages:
  - build
  - deploy

variables:
  STAGING_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  STAGING_LATEST_IMAGE: $CI_REGISTRY_IMAGE:staging
  PROD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  PROD_LATEST_IMAGE: $CI_REGISTRY_IMAGE:latest
  STAGING_URL: "https://api.vh-staging.2serv.eu/profiles/" # this is not used by the service
  PRODUCTION_URL: "https://kli.one/register/"
build_staging:
  image: docker:latest
  stage: build
  services:
    - docker:26.0.0-dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --cache-from $STAGING_LATEST_IMAGE --build-arg GIT_SHA=$CI_COMMIT_SHA -t $STAGING_IMAGE .
    - docker tag $STAGING_IMAGE $STAGING_LATEST_IMAGE
    - docker push $STAGING_IMAGE
    - docker push $STAGING_LATEST_IMAGE
  only:
    - master

deploy_staging:
  variables:
    DB_HOST: "profiledb"
    DB_PORT: 5432
    DB_USER: "dev_registration"
    DB_NAME: "profile"
    DB_PASSWORD: "password"
    APP_PORT: "7471"
    APP_MODE: "release"
    APP_ENV: "staging"
    SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    SENTRY_DSN: ${STAGING_PROFILE_SENTRY_DSN}
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.8.0
  stage: deploy
  tags:
    - staging
  script:
    - for variable in "${!DYN_STAGING@}"; do echo "${variable#DYN_STAGING_}"="${!variable}"; export "${variable#DYN_STAGING_}"="${!variable}"; done;
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - IMAGE_NAME=$STAGING_IMAGE docker compose up -d --remove-orphans
  only:
    - master


build_production:
  image: docker:latest
  stage: build
  services:
    - docker:26.0.0-dind
  script:
    - env
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker build --build-arg GIT_SHA=$CI_COMMIT_SHA -t $PROD_IMAGE .
    - docker push $PROD_IMAGE
  only:
    - tags

deploy_production:
  image: gitlab.bbdev.team:5050/vh/buildutils/buildutil:0.8.0
  stage: deploy
  tags:
    - production
  variables: 
    DB_HOST: ${PROD_PG_HOST}
    DB_PORT: ${PROD_PG_PORT} 
    DB_USER: ${PROD_PROFILE_DB_USER}
    DB_PASSWORD: ${PROD_PROFILE_DB_PASS}
    DB_NAME: ${PROD_PROFILE_DB_NAME}
    APP_PORT: "7471"
    APP_MODE: "release"
    APP_ENV: "production"
    SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    SENTRY_DSN: ${PROD_PROFILE_SENTRY_DSN}
  script:
    - for variable in "${!DYN_PROD@}"; do echo "${variable#DYN_PROD_}"="${!variable}"; export "${variable#DYN_PROD_}"="${!variable}"; done;
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - IMAGE_NAME=$PROD_IMAGE docker compose up -d vh-srv-profile
  only:
    - tags
  when: manual
