services:
  profiledb:
    image: postgres:9.6
    container_name: profiledb
    restart: unless-stopped
    profiles:
      - staging
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /opt/srv-profile-db:/docker-entrypoint-initdb.d
  vh-srv-profile:
    image: "${IMAGE_NAME}"
    container_name: 'vh-srv-profile'
    restart: unless-stopped
    env_file: .env
    cpus: '0.5'
    mem_limit: 250M
    ports:
      - 7471:7471
networks:
  default:
    name: vh
    external: true
