BEGIN;

CREATE TABLE gender_types
(
    name text PRIMARY KEY
);

INSERT INTO gender_types
VALUES ('male'),
       ('female');


CREATE TABLE marital_status_types
(
    name text PRIMARY KEY
);

INSERT INTO marital_status_types
VALUES ('Married'),
       ('Single'),
       ('Other');


CREATE TABLE phone_number_types
(
    name text PRIMARY KEY
);

INSERT INTO phone_number_types
VALUES ('phone'),
       ('WhatsApp'),
       ('Telegram');

CREATE TABLE language_list
(
    code text,
    name text PRIMARY KEY
);

INSERT INTO language_list
VALUES ('ab', 'Abkhaz'),
       ('aa', 'Afar'),
       ('af', 'Afrikaans'),
       ('ak', 'Akan'),
       ('sq', 'Albanian'),
       ('am', 'Amharic'),
       ('ar', 'Arabic'),
       ('an', 'Aragonese'),
       ('hy', 'Armenian'),
       ('as', 'Assamese'),
       ('av', 'Avaric'),
       ('ae', 'Avestan'),
       ('ay', 'Aymara'),
       ('az', 'Azerbaijani'),
       ('bm', 'Bambara'),
       ('ba', 'Bashkir'),
       ('eu', 'Basque'),
       ('be', 'Belarusian'),
       ('bn', 'Bengali'),
       ('bh', 'Bihari'),
       ('bi', 'Bislama'),
       ('bs', 'Bosnian'),
       ('br', 'Breton'),
       ('bg', 'Bulgarian'),
       ('my', 'Burmese'),
       ('ca', 'Catalan; Valencian'),
       ('ch', 'Chamorro'),
       ('ce', 'Chechen'),
       ('ny', 'Chichewa; Chewa; Nyanja'),
       ('zh', 'Chinese'),
       ('cv', 'Chuvash'),
       ('kw', 'Cornish'),
       ('co', 'Corsican'),
       ('cr', 'Cree'),
       ('hr', 'Croatian'),
       ('cs', 'Czech'),
       ('da', 'Danish'),
       ('dv', 'Divehi; Dhivehi; Maldivian;'),
       ('nl', 'Dutch'),
       ('en', 'English'),
       ('eo', 'Esperanto'),
       ('et', 'Estonian'),
       ('ee', 'Ewe'),
       ('fo', 'Faroese'),
       ('fj', 'Fijian'),
       ('fi', 'Finnish'),
       ('fr', 'French'),
       ('ff', 'Fula; Fulah; Pulaar; Pular'),
       ('gl', 'Galician'),
       ('ka', 'Georgian'),
       ('de', 'German'),
       ('el', 'Greek, Modern'),
       ('gn', 'Guaraní'),
       ('gu', 'Gujarati'),
       ('ht', 'Haitian; Haitian Creole'),
       ('ha', 'Hausa'),
       ('he', 'Hebrew'),
       ('hz', 'Herero'),
       ('hi', 'Hindi'),
       ('ho', 'Hiri Motu'),
       ('hu', 'Hungarian'),
       ('ia', 'Interlingua'),
       ('id', 'Indonesian'),
       ('ie', 'Interlingue'),
       ('ga', 'Irish'),
       ('ig', 'Igbo'),
       ('ik', 'Inupiaq'),
       ('io', 'Ido'),
       ('is', 'Icelandic'),
       ('it', 'Italian'),
       ('iu', 'Inuktitut'),
       ('ja', 'Japanese'),
       ('jv', 'Javanese'),
       ('kl', 'Kalaallisut, Greenlandic'),
       ('kn', 'Kannada'),
       ('kr', 'Kanuri'),
       ('ks', 'Kashmiri'),
       ('kk', 'Kazakh'),
       ('km', 'Khmer'),
       ('ki', 'Kikuyu, Gikuyu'),
       ('rw', 'Kinyarwanda'),
       ('ky', 'Kirghiz, Kyrgyz'),
       ('kv', 'Komi'),
       ('kg', 'Kongo'),
       ('ko', 'Korean'),
       ('ku', 'Kurdish'),
       ('kj', 'Kwanyama, Kuanyama'),
       ('la', 'Latin'),
       ('lb', 'Luxembourgish, Letzeburgesch'),
       ('lg', 'Luganda'),
       ('li', 'Limburgish, Limburgan, Limburger'),
       ('ln', 'Lingala'),
       ('lo', 'Lao'),
       ('lt', 'Lithuanian'),
       ('lu', 'Luba-Katanga'),
       ('lv', 'Latvian'),
       ('gv', 'Manx'),
       ('mk', 'Macedonian'),
       ('mg', 'Malagasy'),
       ('ms', 'Malay'),
       ('ml', 'Malayalam'),
       ('mt', 'Maltese'),
       ('mi', 'Māori'),
       ('mr', 'Marathi (Marāṭhī)'),
       ('mh', 'Marshallese'),
       ('mn', 'Mongolian'),
       ('na', 'Nauru'),
       ('nv', 'Navajo, Navaho'),
       ('nb', 'Norwegian Bokmål'),
       ('nd', 'North Ndebele'),
       ('ne', 'Nepali'),
       ('ng', 'Ndonga'),
       ('nn', 'Norwegian Nynorsk'),
       ('no', 'Norwegian'),
       ('ii', 'Nuosu'),
       ('nr', 'South Ndebele'),
       ('oc', 'Occitan'),
       ('oj', 'Ojibwe, Ojibwa'),
       ('cu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic'),
       ('om', 'Oromo'),
       ('or', 'Oriya'),
       ('os', 'Ossetian, Ossetic'),
       ('pa', 'Panjabi, Punjabi'),
       ('pi', 'Pāli'),
       ('fa', 'Persian'),
       ('pl', 'Polish'),
       ('ps', 'Pashto, Pushto'),
       ('pt', 'Portuguese'),
       ('qu', 'Quechua'),
       ('rm', 'Romansh'),
       ('rn', 'Kirundi'),
       ('ro', 'Romanian, Moldavian, Moldovan'),
       ('ru', 'Russian'),
       ('sa', 'Sanskrit (Saṁskṛta)'),
       ('sc', 'Sardinian'),
       ('sd', 'Sindhi'),
       ('se', 'Northern Sami'),
       ('sm', 'Samoan'),
       ('sg', 'Sango'),
       ('sr', 'Serbian'),
       ('gd', 'Scottish Gaelic; Gaelic'),
       ('sn', 'Shona'),
       ('si', 'Sinhala, Sinhalese'),
       ('sk', 'Slovak'),
       ('sl', 'Slovene'),
       ('so', 'Somali'),
       ('st', 'Southern Sotho'),
       ('es', 'Spanish'),
       ('su', 'Sundanese'),
       ('sw', 'Swahili'),
       ('ss', 'Swati'),
       ('sv', 'Swedish'),
       ('ta', 'Tamil'),
       ('te', 'Telugu'),
       ('tg', 'Tajik'),
       ('th', 'Thai'),
       ('ti', 'Tigrinya'),
       ('bo', 'Tibetan Standard, Tibetan, Central'),
       ('tk', 'Turkmen'),
       ('tl', 'Tagalog'),
       ('tn', 'Tswana'),
       ('to', 'Tonga (Tonga Islands)'),
       ('tr', 'Turkish'),
       ('ts', 'Tsonga'),
       ('tt', 'Tatar'),
       ('tw', 'Twi'),
       ('ty', 'Tahitian'),
       ('ug', 'Uighur, Uyghur'),
       ('uk', 'Ukrainian'),
       ('ur', 'Urdu'),
       ('uz', 'Uzbek'),
       ('ve', 'Venda'),
       ('vi', 'Vietnamese'),
       ('vo', 'Volapük'),
       ('wa', 'Walloon'),
       ('cy', 'Welsh'),
       ('wo', 'Wolof'),
       ('fy', 'Western Frisian'),
       ('xh', 'Xhosa'),
       ('yi', 'Yiddish'),
       ('yo', 'Yoruba'),
       ('za', 'Zhuang, Chuang');

CREATE TABLE users
(
    user_id               uuid        NOT NULL PRIMARY KEY,
    keycloak_id           TEXT        NOT NULL UNIQUE,
    updated_at            timestamptz,
    created_at            timestamptz NOT NULL default now(),
    deleted               bool                 default false,
    first_name_latin      text        NOT NULL,
    first_name_vernacular text,
    last_name_latin       text        NOT NULL,
    last_name_vernacular  text,
    street_address        text,
    country               text,
    state_region          text,
    postal_code           text,
    gender                text        NOT NULL REFERENCES gender_types (name),
    marital_status        text        NOT NULL references marital_status_types (name),
    date_of_birth         date,
    primary_email         text        NOT NULL,
    alternate_email_1     text,
    alternate_email_2     text,
    first_language        text        NOT NULL REFERENCES language_list (name),
    other_language_1      text REFERENCES language_list (name),
    other_language_2      text REFERENCES language_list (name),
    other_language_3      text REFERENCES language_list (name),
    other_language_4      text REFERENCES language_list (name),
    listening_language    text        NOT NULL REFERENCES language_list (name),
    reading_language      text        NOT NULL REFERENCES language_list (name),
    email_language        text        NOT NULL REFERENCES language_list (name),
    study_start_year      int         NOT NULL,
    study_framework       text        NOT NULL,
    has_ten_group         boolean     NOT NULL,
    wants_ten_group       boolean,
    name_of_ten_group     text
);

CREATE TABLE phone_numbers
(
    user_id      uuid   NOT NULL REFERENCES users (user_id),
    phone_number bigint NOT NULL,
    type         text   NOT NULL REFERENCES phone_number_types (name),

    UNIQUE (user_id, phone_number)
);

COMMIT;
