BEGIN;

CREATE EXTENSION pgcrypto;

CREATE TABLE gender_types
(
    name text PRIMARY KEY
);

INSERT INTO gender_types
VALUES ('male'),
       ('female');


CREATE TABLE marital_status_types
(
    name text PRIMARY KEY
);

INSERT INTO marital_status_types
VALUES ('Married'),
       ('Single'),
       ('Other');


CREATE TABLE phone_number_types
(
    name text PRIMARY KEY
);

INSERT INTO phone_number_types
VALUES ('mobile'),
       ('WhatsApp'),
       ('Telegram');

CREATE TABLE IF NOT EXISTS "country_list" (
    "name" TEXT NOT NULL,
    "dial_code" TEXT NULL,
    "code" TEXT NOT NULL PRIMARY KEY
);

INSERT INTO country_list VALUES
    ('Afghanistan','93','AF'),
    ('Albania','355','AL'),
    ('Algeria','213','DZ'),
    ('AmericanSamoa','1 684','AS'),
    ('Andorra','376','AD'),
    ('Angola','244','AO'),
    ('Anguilla','1 264','AI'),
    ('Antigua and Barbuda','1268','AG'),
    ('Argentina','54','AR'),
    ('Armenia','374','AM'),
    ('Aruba','297','AW'),
    ('Australia','61','AU'),
    ('Austria','43','AT'),
    ('Azerbaijan','994','AZ'),
    ('Bahamas','1 242','BS'),
    ('Bahrain','973','BH'),
    ('Bangladesh','880','BD'),
    ('Barbados','1 246','BB'),
    ('Belarus','375','BY'),
    ('Belgium','32','BE'),
    ('Belize','501','BZ'),
    ('Benin','229','BJ'),
    ('Bermuda','1 441','BM'),
    ('Bhutan','975','BT'),
    ('Bosnia and Herzegovina','387','BA'),
    ('Botswana','267','BW'),
    ('Brazil','55','BR'),
    ('British Indian Ocean Territory','246','IO'),
    ('Bulgaria','359','BG'),
    ('Burkina Faso','226','BF'),
    ('Burundi','257','BI'),
    ('Cambodia','855','KH'),
    ('Cameroon','237','CM'),
    ('Canada','1','CA'),
    ('Cape Verde','238','CV'),
    ('Cayman Islands','345','KY'),
    ('Central African Republic','236','CF'),
    ('Chad','235','TD'),
    ('Chile','56','CL'),
    ('China','86','CN'),
    ('Christmas Island','61','CX'),
    ('Colombia','57','CO'),
    ('Comoros','269','KM'),
    ('Congo','242','CG'),
    ('Cook Islands','682','CK'),
    ('Costa Rica','506','CR'),
    ('Croatia','385','HR'),
    ('Cuba','53','CU'),
    ('Cyprus','537','CY'),
    ('Czech Republic','420','CZ'),
    ('Denmark','45','DK'),
    ('Djibouti','253','DJ'),
    ('Dominica','1 767','DM'),
    ('Dominican Republic','1 849','DO'),
    ('Ecuador','593','EC'),
    ('Egypt','20','EG'),
    ('El Salvador','503','SV'),
    ('Equatorial Guinea','240','GQ'),
    ('Eritrea','291','ER'),
    ('Estonia','372','EE'),
    ('Ethiopia','251','ET'),
    ('Faroe Islands','298','FO'),
    ('Fiji','679','FJ'),
    ('Finland','358','FI'),
    ('France','33','FR'),
    ('French Guiana','594','GF'),
    ('French Polynesia','689','PF'),
    ('Gabon','241','GA'),
    ('Gambia','220','GM'),
    ('Georgia','995','GE'),
    ('Germany','49','DE'),
    ('Ghana','233','GH'),
    ('Gibraltar','350','GI'),
    ('Greece','30','GR'),
    ('Greenland','299','GL'),
    ('Grenada','1 473','GD'),
    ('Guadeloupe','590','GP'),
    ('Guam','1 671','GU'),
    ('Guatemala','502','GT'),
    ('Guinea','224','GN'),
    ('Guinea-Bissau','245','GW'),
    ('Guyana','595','GY'),
    ('Haiti','509','HT'),
    ('Honduras','504','HN'),
    ('Hungary','36','HU'),
    ('Iceland','354','IS'),
    ('India','91','IN'),
    ('Indonesia','62','ID'),
    ('Iraq','964','IQ'),
    ('Ireland','353','IE'),
    ('Israel','972','IL'),
    ('Italy','39','IT'),
    ('Iran','98','IR'),
    ('Iran, Islamic Republic of','98','IR'),
    ('Jamaica','1 876','JM'),
    ('Japan','81','JP'),
    ('Jordan','962','JO'),
    ('Kazakhstan','7 7','KZ'),
    ('Kenya','254','KE'),
    ('Kiribati','686','KI'),
    ('Kuwait','965','KW'),
    ('Kyrgyzstan','996','KG'),
    ('Latvia','371','LV'),
    ('Lebanon','961','LB'),
    ('Lesotho','266','LS'),
    ('Liberia','231','LR'),
    ('Liechtenstein','423','LI'),
    ('Lithuania','370','LT'),
    ('Luxembourg','352','LU'),
    ('Madagascar','261','MG'),
    ('Malawi','265','MW'),
    ('Malaysia','60','MY'),
    ('Maldives','960','MV'),
    ('Mali','223','ML'),
    ('Malta','356','MT'),
    ('Marshall Islands','692','MH'),
    ('Martinique','596','MQ'),
    ('Mauritania','222','MR'),
    ('Mauritius','230','MU'),
    ('Mayotte','262','YT'),
    ('Mexico','52','MX'),
    ('Moldova','373','MD'),
    ('Monaco','377','MC'),
    ('Mongolia','976','MN'),
    ('Montenegro','382','ME'),
    ('Montserrat','1664','MS'),
    ('Morocco','212','MA'),
    ('Myanmar','95','MM'),
    ('Namibia','264','NA'),
    ('Nauru','674','NR'),
    ('Nepal','977','NP'),
    ('Netherlands','31','NL'),
    ('Netherlands Antilles','599','AN'),
    ('New Caledonia','687','NC'),
    ('New Zealand','64','NZ'),
    ('Nicaragua','505','NI'),
    ('Niger','227','NE'),
    ('Nigeria','234','NG'),
    ('Niue','683','NU'),
    ('Norfolk Island','672','NF'),
    ('Northern Mariana Islands','1 670','MP'),
    ('Norway','47','NO'),
    ('Oman','968','OM'),
    ('Pakistan','92','PK'),
    ('Palau','680','PW'),
    ('Panama','507','PA'),
    ('Papua New Guinea','675','PG'),
    ('Paraguay','595','PY'),
    ('Peru','51','PE'),
    ('Philippines','63','PH'),
    ('Poland','48','PL'),
    ('Portugal','351','PT'),
    ('Puerto Rico','1 939','PR'),
    ('Qatar','974','QA'),
    ('Romania','40','RO'),
    ('Russia','7','RU'),
    ('Rwanda','250','RW'),
    ('Samoa','685','WS'),
    ('San Marino','378','SM'),
    ('Saudi Arabia','966','SA'),
    ('Senegal','221','SN'),
    ('Serbia','381','RS'),
    ('Seychelles','248','SC'),
    ('Sierra Leone','232','SL'),
    ('Singapore','65','SG'),
    ('Slovakia','421','SK'),
    ('Slovenia','386','SI'),
    ('Solomon Islands','677','SB'),
    ('South Africa','27','ZA'),
    ('South Georgia and the South Sandwich Islands','500','GS'),
    ('Spain','34','ES'),
    ('Sri Lanka','94','LK'),
    ('Sudan','249','SD'),
    ('Suriname','597','SR'),
    ('Swaziland','268','SZ'),
    ('Sweden','46','SE'),
    ('Switzerland','41','CH'),
    ('Tajikistan','992','TJ'),
    ('Thailand','66','TH'),
    ('Togo','228','TG'),
    ('Tokelau','690','TK'),
    ('Tonga','676','TO'),
    ('Trinidad and Tobago','1 868','TT'),
    ('Tunisia','216','TN'),
    ('Turkey','90','TR'),
    ('Turkmenistan','993','TM'),
    ('Turks and Caicos Islands','1 649','TC'),
    ('Tuvalu','688','TV'),
    ('Uganda','256','UG'),
    ('Ukraine','380','UA'),
    ('United Arab Emirates','971','AE'),
    ('United Kingdom','44','GB'),
    ('United States','1','US'),
    ('Uruguay','598','UY'),
    ('Uzbekistan','998','UZ'),
    ('Vanuatu','678','VU'),
    ('Wallis and Futuna','681','WF'),
    ('Yemen','967','YE'),
    ('Zambia','260','ZM'),
    ('Zimbabwe','263','ZW'),
    ('land Islands','N/A','AX'),
    ('Antarctica','N/A','AQ'),
    ('Bolivia, Plurinational State of','591','BO'),
    ('Brunei Darussalam','673','BN'),
    ('Cocos (Keeling) Islands','61','CC'),
    ('Congo, The Democratic Republic of the','243','CD'),
    ('Cote d''Ivoire','225','CI'),
    ('Falkland Islands (Malvinas)','500','FK'),
    ('Guernsey','44','GG'),
    ('Holy See (Vatican City State)','379','VA'),
    ('Hong Kong','852','HK'),
    ('Isle of Man','44','IM'),
    ('Jersey','44','JE'),
    ('Korea, Democratic People''s Republic of','850','KP'),
    ('Korea, Republic of','82','KR'),
    ('Lao People''s Democratic Republic','856','LA'),
    ('Libyan Arab Jamahiriya','218','LY'),
    ('Macao','853','MO'),
    ('Macedonia, The Former Yugoslav Republic of','389','MK'),
    ('Micronesia, Federated States of','691','FM'),
    ('Moldova, Republic of','373','MD'),
    ('Mozambique','258','MZ'),
    ('Palestinian Territory','970','PS'),
    ('Pitcairn','872','PN'),
    ('Réunion','262','RE'),
    ('Saint Barthélemy','590','BL'),
    ('Saint Helena, Ascension and Tristan Da Cunha','290','SH'),
    ('Saint Kitts and Nevis','1 869','KN'),
    ('Saint Lucia','1 758','LC'),
    ('Saint Martin','590','MF'),
    ('Saint Pierre and Miquelon','508','PM'),
    ('Saint Vincent and the Grenadines','1 784','VC'),
    ('Sao Tome and Principe','239','ST'),
    ('Somalia','252','SO'),
    ('Svalbard and Jan Mayen','47','SJ'),
    ('Syrian Arab Republic','963','SY'),
    ('Taiwan','886','TW'),
    ('Tanzania, United Republic of','255','TZ'),
    ('Timor-Leste','670','TL'),
    ('Venezuela, Bolivarian Republic of','58','VE'),
    ('Viet Nam','84','VN'),
    ('Virgin Islands, British','1 284','VG'),
    ('Virgin Islands, U.S.','1 340','VI');

CREATE TABLE language_list
(
    code text PRIMARY KEY,
    name text
);

INSERT INTO language_list
VALUES ('ab', 'Abkhaz'),
       ('aa', 'Afar'),
       ('af', 'Afrikaans'),
       ('ak', 'Akan'),
       ('sq', 'Albanian'),
       ('am', 'Amharic'),
       ('ar', 'Arabic'),
       ('an', 'Aragonese'),
       ('hy', 'Armenian'),
       ('as', 'Assamese'),
       ('av', 'Avaric'),
       ('ae', 'Avestan'),
       ('ay', 'Aymara'),
       ('az', 'Azerbaijani'),
       ('bm', 'Bambara'),
       ('ba', 'Bashkir'),
       ('eu', 'Basque'),
       ('be', 'Belarusian'),
       ('bn', 'Bengali'),
       ('bh', 'Bihari'),
       ('bi', 'Bislama'),
       ('bs', 'Bosnian'),
       ('br', 'Breton'),
       ('bg', 'Bulgarian'),
       ('my', 'Burmese'),
       ('ca', 'Catalan; Valencian'),
       ('ch', 'Chamorro'),
       ('ce', 'Chechen'),
       ('ny', 'Chichewa; Chewa; Nyanja'),
       ('zh', 'Chinese'),
       ('cv', 'Chuvash'),
       ('kw', 'Cornish'),
       ('co', 'Corsican'),
       ('cr', 'Cree'),
       ('hr', 'Croatian'),
       ('cs', 'Czech'),
       ('da', 'Danish'),
       ('dv', 'Divehi; Dhivehi; Maldivian;'),
       ('nl', 'Dutch'),
       ('en', 'English'),
       ('eo', 'Esperanto'),
       ('et', 'Estonian'),
       ('ee', 'Ewe'),
       ('fo', 'Faroese'),
       ('fj', 'Fijian'),
       ('fi', 'Finnish'),
       ('fr', 'French'),
       ('ff', 'Fula; Fulah; Pulaar; Pular'),
       ('gl', 'Galician'),
       ('ka', 'Georgian'),
       ('de', 'German'),
       ('el', 'Greek, Modern'),
       ('gn', 'Guaraní'),
       ('gu', 'Gujarati'),
       ('ht', 'Haitian; Haitian Creole'),
       ('ha', 'Hausa'),
       ('he', 'Hebrew'),
       ('hz', 'Herero'),
       ('hi', 'Hindi'),
       ('ho', 'Hiri Motu'),
       ('hu', 'Hungarian'),
       ('ia', 'Interlingua'),
       ('id', 'Indonesian'),
       ('ie', 'Interlingue'),
       ('ga', 'Irish'),
       ('ig', 'Igbo'),
       ('ik', 'Inupiaq'),
       ('io', 'Ido'),
       ('is', 'Icelandic'),
       ('it', 'Italian'),
       ('iu', 'Inuktitut'),
       ('ja', 'Japanese'),
       ('jv', 'Javanese'),
       ('kl', 'Kalaallisut, Greenlandic'),
       ('kn', 'Kannada'),
       ('kr', 'Kanuri'),
       ('ks', 'Kashmiri'),
       ('kk', 'Kazakh'),
       ('km', 'Khmer'),
       ('ki', 'Kikuyu, Gikuyu'),
       ('rw', 'Kinyarwanda'),
       ('ky', 'Kirghiz, Kyrgyz'),
       ('kv', 'Komi'),
       ('kg', 'Kongo'),
       ('ko', 'Korean'),
       ('ku', 'Kurdish'),
       ('kj', 'Kwanyama, Kuanyama'),
       ('la', 'Latin'),
       ('lb', 'Luxembourgish, Letzeburgesch'),
       ('lg', 'Luganda'),
       ('li', 'Limburgish, Limburgan, Limburger'),
       ('ln', 'Lingala'),
       ('lo', 'Lao'),
       ('lt', 'Lithuanian'),
       ('lu', 'Luba-Katanga'),
       ('lv', 'Latvian'),
       ('gv', 'Manx'),
       ('mk', 'Macedonian'),
       ('mg', 'Malagasy'),
       ('ms', 'Malay'),
       ('ml', 'Malayalam'),
       ('mt', 'Maltese'),
       ('mi', 'Māori'),
       ('mr', 'Marathi (Marāṭhī)'),
       ('mh', 'Marshallese'),
       ('mn', 'Mongolian'),
       ('na', 'Nauru'),
       ('nv', 'Navajo, Navaho'),
       ('nb', 'Norwegian Bokmål'),
       ('nd', 'North Ndebele'),
       ('ne', 'Nepali'),
       ('ng', 'Ndonga'),
       ('nn', 'Norwegian Nynorsk'),
       ('no', 'Norwegian'),
       ('ii', 'Nuosu'),
       ('nr', 'South Ndebele'),
       ('oc', 'Occitan'),
       ('oj', 'Ojibwe, Ojibwa'),
       ('cu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic'),
       ('om', 'Oromo'),
       ('or', 'Oriya'),
       ('os', 'Ossetian, Ossetic'),
       ('pa', 'Panjabi, Punjabi'),
       ('pi', 'Pāli'),
       ('fa', 'Persian'),
       ('pl', 'Polish'),
       ('ps', 'Pashto, Pushto'),
       ('pt', 'Portuguese'),
       ('qu', 'Quechua'),
       ('rm', 'Romansh'),
       ('rn', 'Kirundi'),
       ('ro', 'Romanian, Moldavian, Moldovan'),
       ('ru', 'Russian'),
       ('sa', 'Sanskrit (Saṁskṛta)'),
       ('sc', 'Sardinian'),
       ('sd', 'Sindhi'),
       ('se', 'Northern Sami'),
       ('sm', 'Samoan'),
       ('sg', 'Sango'),
       ('sr', 'Serbian'),
       ('gd', 'Scottish Gaelic; Gaelic'),
       ('sn', 'Shona'),
       ('si', 'Sinhala, Sinhalese'),
       ('sk', 'Slovak'),
       ('sl', 'Slovene'),
       ('so', 'Somali'),
       ('st', 'Southern Sotho'),
       ('es', 'Spanish'),
       ('su', 'Sundanese'),
       ('sw', 'Swahili'),
       ('ss', 'Swati'),
       ('sv', 'Swedish'),
       ('ta', 'Tamil'),
       ('te', 'Telugu'),
       ('tg', 'Tajik'),
       ('th', 'Thai'),
       ('ti', 'Tigrinya'),
       ('bo', 'Tibetan Standard, Tibetan, Central'),
       ('tk', 'Turkmen'),
       ('tl', 'Tagalog'),
       ('tn', 'Tswana'),
       ('to', 'Tonga (Tonga Islands)'),
       ('tr', 'Turkish'),
       ('ts', 'Tsonga'),
       ('tt', 'Tatar'),
       ('tw', 'Twi'),
       ('ty', 'Tahitian'),
       ('ug', 'Uighur, Uyghur'),
       ('uk', 'Ukrainian'),
       ('ur', 'Urdu'),
       ('uz', 'Uzbek'),
       ('ve', 'Venda'),
       ('vi', 'Vietnamese'),
       ('vo', 'Volapük'),
       ('wa', 'Walloon'),
       ('cy', 'Welsh'),
       ('wo', 'Wolof'),
       ('fy', 'Western Frisian'),
       ('xh', 'Xhosa'),
       ('yi', 'Yiddish'),
       ('yo', 'Yoruba'),
       ('za', 'Zhuang, Chuang');

CREATE TABLE users
(
    user_id               uuid        NOT NULL PRIMARY KEY default gen_random_uuid(),
    keycloak_id           TEXT        NOT NULL UNIQUE,
    updated_at            timestamptz NOT NULL             default now(),
    created_at            timestamptz NOT NULL             default now(),
    deleted               bool                             default false,
    first_name_latin      text,
    first_name_vernacular text        NOT NULL,
    last_name_latin       text,
    last_name_vernacular  text        NOT NULL,
    street_address        text,
    country               text,
    state_region          text,
    postal_code           text,
    city                  text,
    gender                text REFERENCES gender_types (name),
    marital_status        text REFERENCES marital_status_types (name),
    date_of_birth         date,
    primary_email         text        NOT NULL,
    alternate_email_1     text,
    alternate_email_2     text,
    first_language        text REFERENCES language_list (code),
    other_language_1      text REFERENCES language_list (code),
    other_language_2      text REFERENCES language_list (code),
    other_language_3      text REFERENCES language_list (code),
    other_language_4      text REFERENCES language_list (code),
    listening_language    text REFERENCES language_list (code),
    reading_language      text REFERENCES language_list (code),
    email_language        text REFERENCES language_list (code),
    study_start_year      int,
    study_framework       text,
    has_ten_group         boolean,
    wants_ten_group       boolean,
    name_of_ten_group     text
);

CREATE TABLE phone_numbers
(
    user_id      uuid NOT NULL REFERENCES users (user_id),
    phone_number text NOT NULL,
    type         text NOT NULL REFERENCES phone_number_types (name),

    UNIQUE (user_id, type)
);

COMMIT;
