package membership

import (
	"context"
	"errors"
	"fmt"
	"log"

	"gitlab.bbdev.team/vh/vh-srv-profile/common"
	"gitlab.bbdev.team/vh/vh-srv-profile/pkg/keycloak"
	"gitlab.bbdev.team/vh/vh-srv-profile/pkg/orders"
	"gitlab.bbdev.team/vh/vh-srv-profile/repo"
)

var interestingEvents = map[string]struct{}{
	//orders.TypeCreateAccount: {},
	//orders.TypeUpdateAccount: {},
	//orders.TypeDeleteAccount: {},
	//orders.TypeHardDeleteAccount: {},
	orders.TypeCreateOrder:   {},
	orders.TypeUpdateOrder:   {},
	orders.TypeDeleteOrder:   {},
	orders.TypeCreatePayment: {},
	orders.TypeUpdatePayment: {},
	orders.TypeDeletePayment: {},
	orders.TypeDeleteSpecial: {},
}

var errSkip = errors.New("skip event")

type EventsHandler struct {
	repo          repo.ProfileRepository
	kcTokenSource keycloak.TokenSource
	ordersService orders.OrdersService
}

func NewEventsHandler(repo repo.ProfileRepository) *EventsHandler {
	eh := new(EventsHandler)
	eh.repo = repo
	eh.kcTokenSource = keycloak.NewServiceClient()
	eh.ordersService = orders.NewOrdersAPI()
	return eh
}

func (eh *EventsHandler) HandleOrdersEvent(event orders.Event) {
	if eh.shouldSkip(event) {
		return
	}

	ctx := context.WithValue(context.Background(), common.CtxTokenSource, eh.kcTokenSource)

	userIDs, err := eh.getUserIDs(ctx, event)
	if err != nil {
		if !errors.Is(err, errSkip) {
			log.Printf("ERROR: membership.EventsHandler.handleOrdersEvent getUserIDs: %v\n", err)
		}
		return
	}

	if userIDs == nil {
		log.Printf("WARNING: membership.EventsHandler.handleOrdersEvent no user IDs: %s %+v\n",
			event.Type, event.Payload)
		return
	}

	// TODO (edo): uncomment when we go live with v2
	log.Printf("INFO: membership.EventsHandler.handleOrdersEvent would have eval membership for %s %s\n",
		*userIDs.Email, *userIDs.KeycloakID)
	//_, err = eh.repo.EvaluateMembershipByUserID(ctx, *userIDs)
	//if err != nil {
	//	log.Printf("ERROR: membership.EventsHandler.handleOrdersEvent repo.EvaluateMembershipByUserID: %v\n", err)
	//}
}

func (eh *EventsHandler) shouldSkip(event orders.Event) bool {
	// skip events with no direct impact of membership
	if _, ok := interestingEvents[event.Type]; !ok {
		return true
	}

	// skip events generated by our cron jobs
	if event.Component == orders.ComponentAPI && event.Actor == common.ServiceName {
		return true
	}

	// skip part of robokasa importer chain (account? -> order -> payment)
	if event.Component == orders.ComponentRobokasaImporter && event.Type != orders.TypeCreatePayment {
		return true
	}

	return false
}

func (eh *EventsHandler) getUserIDs(ctx context.Context, event orders.Event) (*repo.EmailKeycloakAndUserIDBody, error) {
	switch event.Type {
	case orders.TypeCreateOrder, orders.TypeUpdateOrder, orders.TypeDeleteOrder:
		orderID := event.Payload["order_id"].(float64)
		return eh.getUserIDsFromOrder(ctx, int(orderID))
	case orders.TypeCreatePayment, orders.TypeUpdatePayment, orders.TypeDeletePayment:
		paymentID := event.Payload["payment_id"].(float64)
		return eh.getUserIDsFromPayment(ctx, event, int(paymentID))
	case orders.TypeDeleteSpecial:
		email := event.Payload["email"].(string)
		return &repo.EmailKeycloakAndUserIDBody{Email: &email}, nil
	}

	return nil, fmt.Errorf("unsupported event type: %s", event.Type)
}

func (eh *EventsHandler) getUserIDsFromOrder(ctx context.Context, orderID int) (*repo.EmailKeycloakAndUserIDBody, error) {
	order, err := eh.ordersService.GetOrderByID(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetOrderByID: %w", err)
	}

	account, err := eh.ordersService.GetAccountByID(ctx, order.AccountID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetAccountByID: %w", err)
	}

	return &repo.EmailKeycloakAndUserIDBody{
		Email:      &account.Email,
		KeycloakID: &account.UserKey,
	}, nil
}

func (eh *EventsHandler) getUserIDsFromPayment(ctx context.Context, event orders.Event, paymentID int) (*repo.EmailKeycloakAndUserIDBody, error) {
	payment, err := eh.ordersService.GetPaymentByID(ctx, paymentID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetPaymentByID: %w", err)
	}

	if event.Type == orders.TypeCreatePayment && payment.PaymentStatus == "pending" {
		return nil, errSkip
	}

	return eh.getUserIDsFromOrder(ctx, payment.OrderID)
}
