package membership

import (
	"context"
	"errors"
	"fmt"
	"log/slog"

	"github.com/getsentry/sentry-go"

	"gitlab.bbdev.team/vh/vh-srv-profile/common"
	"gitlab.bbdev.team/vh/vh-srv-profile/pkg/keycloak"
	"gitlab.bbdev.team/vh/vh-srv-profile/pkg/orders"
	"gitlab.bbdev.team/vh/vh-srv-profile/pkg/utils"
	"gitlab.bbdev.team/vh/vh-srv-profile/repo"
)

var interestingEvents = map[string]struct{}{
	//orders.TypeCreateAccount: {},
	//orders.TypeUpdateAccount: {},
	//orders.TypeDeleteAccount: {},
	//orders.TypeHardDeleteAccount: {},
	orders.TypeMergeAccount:  {},
	orders.TypeCreateOrder:   {},
	orders.TypeUpdateOrder:   {},
	orders.TypeDeleteOrder:   {},
	orders.TypeCreatePayment: {},
	orders.TypeUpdatePayment: {},
	orders.TypeDeletePayment: {},
	orders.TypeDeleteSpecial: {},
}

var errSkip = errors.New("skip event")

type EventsHandler struct {
	repo          repo.ProfileRepository
	kcTokenSource keycloak.TokenSource
	ordersService orders.OrdersService
}

func NewEventsHandler(repo repo.ProfileRepository) *EventsHandler {
	eh := new(EventsHandler)
	eh.repo = repo
	eh.kcTokenSource = keycloak.NewServiceClient()
	eh.ordersService = orders.NewOrdersAPI()
	return eh
}

func (eh *EventsHandler) HandleOrdersEvent(event orders.Event) {
	ctx := eh.newContext(event)

	if eh.shouldSkip(event) {
		return
	}

	userIDs, err := eh.getUserIDs(ctx, event)
	if err != nil {
		if !errors.Is(err, errSkip) {
			utils.LogFor(ctx).Error("membership.EventsHandler.HandleOrdersEvent getUserIDs", slog.Any("err", err))
			sentry.CaptureException(err)
		}
		return
	}

	if userIDs == nil {
		utils.LogFor(ctx).Warn("membership.EventsHandler.HandleOrdersEvent no user IDs",
			slog.String("event_type", event.Type), slog.Any("event_payload", event.Payload))
		sentry.CaptureMessage("membership.EventsHandler.HandleOrdersEvent no user IDs")
		return
	}

	_, err = eh.repo.EvaluateMembershipByUserID(ctx, *userIDs)
	if err != nil {
		utils.LogFor(ctx).Error("membership.EventsHandler.HandleOrdersEvent repo.EvaluateMembershipByUserID", slog.Any("err", err))
		sentry.CaptureException(err)
	}
}

func (eh *EventsHandler) newContext(event orders.Event) context.Context {
	logger := slog.Default().With(slog.String("nats_nuid", event.ID))
	ctx := context.WithValue(context.Background(), common.CtxLogger, logger)
	ctx = context.WithValue(ctx, common.CtxTokenSource, eh.kcTokenSource)

	hub := sentry.CurrentHub().Clone()
	hub.ConfigureScope(func(scope *sentry.Scope) {
		scope.SetTag("nats_nuid", event.ID)
	})
	ctx = sentry.SetHubOnContext(ctx, hub)

	return ctx
}

func (eh *EventsHandler) shouldSkip(event orders.Event) bool {
	// skip events with no direct impact of membership
	if _, ok := interestingEvents[event.Type]; !ok {
		return true
	}

	// skip events generated by our cron jobs
	if event.Component == orders.ComponentAPI && event.Actor == common.ServiceName {
		return true
	}

	// skip part of robokasa importer chain (account? -> order -> payment)
	if event.Component == orders.ComponentRobokasaImporter && event.Type != orders.TypeCreatePayment {
		return true
	}

	return false
}

func (eh *EventsHandler) getUserIDs(ctx context.Context, event orders.Event) (*repo.EmailKeycloakAndUserIDBody, error) {
	switch event.Type {
	case orders.TypeCreateOrder, orders.TypeUpdateOrder, orders.TypeDeleteOrder:
		orderID := event.Payload["order_id"].(float64)
		return eh.getUserIDsFromOrder(ctx, int(orderID))
	case orders.TypeCreatePayment, orders.TypeUpdatePayment, orders.TypeDeletePayment:
		paymentID := event.Payload["payment_id"].(float64)
		return eh.getUserIDsFromPayment(ctx, event, int(paymentID))
	case orders.TypeDeleteSpecial:
		email := event.Payload["email"].(string)
		return &repo.EmailKeycloakAndUserIDBody{Email: &email}, nil
	case orders.TypeMergeAccount:
		return eh.mergeAccounts(ctx, event)
	}

	return nil, fmt.Errorf("unsupported event type: %s", event.Type)
}

func (eh *EventsHandler) mergeAccounts(ctx context.Context, event orders.Event) (*repo.EmailKeycloakAndUserIDBody, error) {
	var mergeData = repo.AccountsMergeData{event.Payload["source_account_id"].(string),
		event.Payload["destination_account_id"].(string),
		event.Payload["source_account_email"].(string),
		event.Payload["destination_account_email"].(string)}
	res, err := eh.repo.MergeAccounts(ctx, mergeData)
	if err != nil {
		return nil, fmt.Errorf("EventsHandler.mergeAccounts: %w", err)
	}
	return res, nil

}

func (eh *EventsHandler) getUserIDsFromOrder(ctx context.Context, orderID int) (*repo.EmailKeycloakAndUserIDBody, error) {
	order, err := eh.ordersService.GetOrderByID(ctx, orderID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetOrderByID: %w", err)
	}

	account, err := eh.ordersService.GetAccountByID(ctx, order.AccountID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetAccountByID: %w", err)
	}

	return &repo.EmailKeycloakAndUserIDBody{
		Email:      &account.Email,
		KeycloakID: &account.UserKey,
	}, nil
}

func (eh *EventsHandler) getUserIDsFromPayment(ctx context.Context, event orders.Event, paymentID int) (*repo.EmailKeycloakAndUserIDBody, error) {
	payment, err := eh.ordersService.GetPaymentByID(ctx, paymentID)
	if err != nil {
		return nil, fmt.Errorf("ordersService.GetPaymentByID: %w", err)
	}

	if event.Type == orders.TypeCreatePayment && payment.PaymentStatus == "pending" {
		return nil, errSkip
	}

	return eh.getUserIDsFromOrder(ctx, payment.OrderID)
}
